server:
  port: 8090
  servlet:
    context-path: /security-platform


spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://139.9.225.140:3306/security?useUnicode=true&useSSL=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Rbi@20191006@Rbi
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  file:
    path: security_web.log
  pattern:

uploadfile.ip: http://192.168.28.100
hiddenPath: /hidden/
excelWritePath: /excelWritePath/
seriousDangerPath: /seriousDanger/
riskPath: /riskControl/
spcialPath: /spcial/
