server:
  port: 8090
  servlet:
    context-path: /security-platform

spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://120.77.171.73:3306/security?useUnicode=true&useSSL=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Rbi@2018
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  file:
    path: security_web.log
  pattern:
#    console: %d{yyyy/MM/dd-HH:mm:ss} -- %(${PID:- }) --- [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy/MM/dd-HH:mm} -- %(${PID:- }) --- [%thread] %-5level %logger- %msg%n

uploadfile.ip: http://120.77.171.73
path2:
hiddenPath: /usr/work/wx/hidden/
excelWritePath: /usr/work/wx/excelWritePath/
seriousDangerPath: /usr/work/wx/seriousDanger/
riskPath: /usr/work/wx/riskControl/
spcialPath: /usr/work/wx/special/


