server:
  port: 8090
  servlet:
    context-path: /security-platform

spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:sqlserver://139.9.225.140:3306/security?useUnicode=true&useSSL=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: Rbi@20191006@Rbi
    sql-script-encoding: utf-8
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  file:
    path: security_web.log
  pattern:
#    console: %d{yyyy/MM/dd-HH:mm:ss} -- %(${PID:- }) --- [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy/MM/dd-HH:mm} -- %(${PID:- }) --- [%thread] %-5level %logger- %msg%n


uploadfile.ip: http://139.9.153.27
hiddenPath: /usr/work/wx/hidden/
excelWritePath: /usr/work/wx/excelWritePath/
seriousDangerPath: /usr/work/wx/seriousDanger/
riskPath: /usr/work/wx/riskControl/
